name: Build Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Get version from Gradle
        id: get_version
        run: echo "VERSION=$(./gradlew -q properties | grep ^version: | awk '{print $2}')" >> $GITHUB_ENV


      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: plugin-artifact-${{ env.VERSION }}
          path: build/distributions/*.zip
          overwrite: true